version: '3.8'

services:
  backend:
    image: myapp-backend:latest
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devoir_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devoir_db
    ports:
      - "3306:3306"

  frontend:
    image: myapp-frontend:latest
    build:
      context: ./Frontend
    ports:
      -"80:80"