name: CI/CD - Full Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: your_secure_password  # Set a strong password for MySQL
          MYSQL_ALLOW_EMPTY_PASSWORD: "no"          # Disable empty passwords for security
          MYSQL_DATABASE: devoir_db
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean install -DskipTests

      - name: Run backend tests
        run: mvn test

  build-and-test-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [build-and-test-backend]  # Ensures frontend builds after backend tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install frontend dependencies
        run: |
          cd Frontend 
          npm install 

      - name: Build frontend
        run: |
          cd Frontend  
          npm run build

  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [build-and-test-frontend]  # Ensures Docker image is built after frontend build
    steps:
      - uses: actions/checkout@v3

      - name: Build backend Docker image
        run: docker build -t myapp-backend:latest ./Backend

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: docker-build  # Ensures deployment happens after Docker image build
    steps:
      - uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Deploy using Docker Compose
        run: docker-compose -f docker-compose.prod.yml up -d

      - name: Print deployment status
        run: docker ps
